 #pragma once
#include <napi.h>
#include "_napi_macro.h"
#include <Windows.h>

using namespace Napi;

#define gd(key) global.Set(#key, key);

Value globalDefine(const CallbackInfo &info)
{
  nm_init;
  Napi::Object global;

  if (info.Length() && nmi_is_obj(0))
  {
    global = nmi_obj(0);
  }
  else
  {
    global = env.Global();
  }

  
  /*
   * Window Messages
   */
  gd(WM_NULL);gd(WM_CREATE);gd(WM_DESTROY);gd(WM_MOVE);gd(WM_SIZE);gd(WM_ACTIVATE);gd(WM_SETFOCUS);gd(WM_KILLFOCUS);gd(WM_ENABLE);gd(WM_SETREDRAW);gd(WM_SETTEXT);gd(WM_GETTEXT);gd(WM_GETTEXTLENGTH);gd(WM_PAINT);gd(WM_CLOSE);gd(WM_QUERYENDSESSION);gd(WM_QUERYOPEN);gd(WM_ENDSESSION);gd(WM_QUIT);gd(WM_ERASEBKGND);gd(WM_SYSCOLORCHANGE);gd(WM_SHOWWINDOW);gd(WM_WININICHANGE);gd(WM_SETTINGCHANGE);gd(WM_DEVMODECHANGE);gd(WM_ACTIVATEAPP);gd(WM_FONTCHANGE);gd(WM_TIMECHANGE);gd(WM_CANCELMODE);gd(WM_SETCURSOR);gd(WM_MOUSEACTIVATE);gd(WM_CHILDACTIVATE);gd(WM_QUEUESYNC);gd(WM_GETMINMAXINFO);gd(WM_PAINTICON);gd(WM_ICONERASEBKGND);gd(WM_NEXTDLGCTL);gd(WM_SPOOLERSTATUS);gd(WM_DRAWITEM);gd(WM_MEASUREITEM);gd(WM_DELETEITEM);gd(WM_VKEYTOITEM);gd(WM_CHARTOITEM);gd(WM_SETFONT);gd(WM_GETFONT);gd(WM_SETHOTKEY);gd(WM_GETHOTKEY);gd(WM_QUERYDRAGICON);gd(WM_COMPAREITEM);gd(WM_GETOBJECT);gd(WM_COMPACTING);gd(WM_COMMNOTIFY);gd(WM_WINDOWPOSCHANGING);gd(WM_WINDOWPOSCHANGED);gd(WM_POWER);gd(WM_COPYDATA);gd(WM_CANCELJOURNAL);gd(WM_NOTIFY);gd(WM_INPUTLANGCHANGEREQUEST);gd(WM_INPUTLANGCHANGE);gd(WM_TCARD);gd(WM_HELP);gd(WM_USERCHANGED);gd(WM_NOTIFYFORMAT);gd(WM_CONTEXTMENU);gd(WM_STYLECHANGING);gd(WM_STYLECHANGED);gd(WM_DISPLAYCHANGE);gd(WM_GETICON);gd(WM_SETICON);gd(WM_NCCREATE);gd(WM_NCDESTROY);gd(WM_NCCALCSIZE);gd(WM_NCHITTEST);gd(WM_NCPAINT);gd(WM_NCACTIVATE);gd(WM_GETDLGCODE);gd(WM_SYNCPAINT);gd(WM_NCMOUSEMOVE);gd(WM_NCLBUTTONDOWN);gd(WM_NCLBUTTONUP);gd(WM_NCLBUTTONDBLCLK);gd(WM_NCRBUTTONDOWN);gd(WM_NCRBUTTONUP);gd(WM_NCRBUTTONDBLCLK);gd(WM_NCMBUTTONDOWN);gd(WM_NCMBUTTONUP);gd(WM_NCMBUTTONDBLCLK);gd(WM_NCXBUTTONDOWN);gd(WM_NCXBUTTONUP);gd(WM_NCXBUTTONDBLCLK);gd(WM_INPUT_DEVICE_CHANGE);gd(WM_INPUT);gd(WM_KEYFIRST);gd(WM_KEYDOWN);gd(WM_KEYUP);gd(WM_CHAR);gd(WM_DEADCHAR);gd(WM_SYSKEYDOWN);gd(WM_SYSKEYUP);gd(WM_SYSCHAR);gd(WM_SYSDEADCHAR);gd(WM_UNICHAR);gd(WM_KEYLAST);gd(WM_KEYLAST);gd(WM_IME_STARTCOMPOSITION);gd(WM_IME_ENDCOMPOSITION);gd(WM_IME_COMPOSITION);gd(WM_IME_KEYLAST);gd(WM_INITDIALOG);gd(WM_COMMAND);gd(WM_SYSCOMMAND);gd(WM_TIMER);gd(WM_HSCROLL);gd(WM_VSCROLL);gd(WM_INITMENU);gd(WM_INITMENUPOPUP);gd(WM_GESTURE);gd(WM_GESTURENOTIFY);gd(WM_MENUSELECT);gd(WM_MENUCHAR);gd(WM_ENTERIDLE);gd(WM_MENURBUTTONUP);gd(WM_MENUDRAG);gd(WM_MENUGETOBJECT);gd(WM_UNINITMENUPOPUP);gd(WM_MENUCOMMAND);gd(WM_CHANGEUISTATE);gd(WM_UPDATEUISTATE);gd(WM_QUERYUISTATE);gd(WM_CTLCOLORMSGBOX);gd(WM_CTLCOLOREDIT);gd(WM_CTLCOLORLISTBOX);gd(WM_CTLCOLORBTN);gd(WM_CTLCOLORDLG);gd(WM_CTLCOLORSCROLLBAR);gd(WM_CTLCOLORSTATIC);gd(WM_MOUSEFIRST);gd(WM_MOUSEMOVE);gd(WM_LBUTTONDOWN);gd(WM_LBUTTONUP);gd(WM_LBUTTONDBLCLK);gd(WM_RBUTTONDOWN);gd(WM_RBUTTONUP);gd(WM_RBUTTONDBLCLK);gd(WM_MBUTTONDOWN);gd(WM_MBUTTONUP);gd(WM_MBUTTONDBLCLK);gd(WM_MOUSEWHEEL);gd(WM_XBUTTONDOWN);gd(WM_XBUTTONUP);gd(WM_XBUTTONDBLCLK);gd(WM_MOUSEHWHEEL);gd(WM_MOUSELAST);gd(WM_MOUSELAST);gd(WM_MOUSELAST);gd(WM_MOUSELAST);gd(WM_PARENTNOTIFY);gd(WM_ENTERMENULOOP);gd(WM_EXITMENULOOP);gd(WM_NEXTMENU);gd(WM_SIZING);gd(WM_CAPTURECHANGED);gd(WM_MOVING);gd(WM_POWERBROADCAST);gd(WM_DEVICECHANGE);gd(WM_MDICREATE);gd(WM_MDIDESTROY);gd(WM_MDIACTIVATE);gd(WM_MDIRESTORE);gd(WM_MDINEXT);gd(WM_MDIMAXIMIZE);gd(WM_MDITILE);gd(WM_MDICASCADE);gd(WM_MDIICONARRANGE);gd(WM_MDIGETACTIVE);gd(WM_MDISETMENU);gd(WM_ENTERSIZEMOVE);gd(WM_EXITSIZEMOVE);gd(WM_DROPFILES);gd(WM_MDIREFRESHMENU);gd(WM_POINTERDEVICECHANGE);gd(WM_POINTERDEVICEINRANGE);gd(WM_POINTERDEVICEOUTOFRANGE);gd(WM_TOUCH);gd(WM_NCPOINTERUPDATE);gd(WM_NCPOINTERDOWN);gd(WM_NCPOINTERUP);gd(WM_POINTERUPDATE);gd(WM_POINTERDOWN);gd(WM_POINTERUP);gd(WM_POINTERENTER);gd(WM_POINTERLEAVE);gd(WM_POINTERACTIVATE);gd(WM_POINTERCAPTURECHANGED);gd(WM_TOUCHHITTESTING);gd(WM_POINTERWHEEL);gd(WM_POINTERHWHEEL);gd(WM_POINTERROUTEDTO);gd(WM_POINTERROUTEDAWAY);gd(WM_POINTERROUTEDRELEASED);gd(WM_IME_SETCONTEXT);gd(WM_IME_NOTIFY);gd(WM_IME_CONTROL);gd(WM_IME_COMPOSITIONFULL);gd(WM_IME_SELECT);gd(WM_IME_CHAR);gd(WM_IME_REQUEST);gd(WM_IME_KEYDOWN);gd(WM_IME_KEYUP);gd(WM_MOUSEHOVER);gd(WM_MOUSELEAVE);gd(WM_NCMOUSEHOVER);gd(WM_NCMOUSELEAVE);gd(WM_WTSSESSION_CHANGE);gd(WM_TABLET_FIRST);gd(WM_TABLET_LAST);gd(WM_DPICHANGED);gd(WM_DPICHANGED_BEFOREPARENT);gd(WM_DPICHANGED_AFTERPARENT);gd(WM_GETDPISCALEDSIZE);gd(WM_CUT);gd(WM_COPY);gd(WM_PASTE);gd(WM_CLEAR);gd(WM_UNDO);gd(WM_RENDERFORMAT);gd(WM_RENDERALLFORMATS);gd(WM_DESTROYCLIPBOARD);gd(WM_DRAWCLIPBOARD);gd(WM_PAINTCLIPBOARD);gd(WM_VSCROLLCLIPBOARD);gd(WM_SIZECLIPBOARD);gd(WM_ASKCBFORMATNAME);gd(WM_CHANGECBCHAIN);gd(WM_HSCROLLCLIPBOARD);gd(WM_QUERYNEWPALETTE);gd(WM_PALETTEISCHANGING);gd(WM_PALETTECHANGED);gd(WM_HOTKEY);gd(WM_PRINT);gd(WM_PRINTCLIENT);gd(WM_APPCOMMAND);gd(WM_THEMECHANGED);gd(WM_CLIPBOARDUPDATE);gd(WM_DWMCOMPOSITIONCHANGED);gd(WM_DWMNCRENDERINGCHANGED);gd(WM_DWMCOLORIZATIONCOLORCHANGED);gd(WM_DWMWINDOWMAXIMIZEDCHANGE);gd(WM_DWMSENDICONICTHUMBNAIL);gd(WM_DWMSENDICONICLIVEPREVIEWBITMAP);gd(WM_GETTITLEBARINFOEX);gd(WM_HANDHELDFIRST);gd(WM_HANDHELDLAST);gd(WM_AFXFIRST);gd(WM_AFXLAST);gd(WM_PENWINFIRST);gd(WM_PENWINLAST);gd(WM_APP);gd(WM_USER);

  /*
   * Window Styles
   */
  gd(WS_OVERLAPPED);gd(WS_POPUP);gd(WS_CHILD);gd(WS_MINIMIZE);gd(WS_VISIBLE);gd(WS_DISABLED);gd(WS_CLIPSIBLINGS);gd(WS_CLIPCHILDREN);gd(WS_MAXIMIZE);gd(WS_CAPTION);gd(WS_BORDER);gd(WS_DLGFRAME);gd(WS_VSCROLL);gd(WS_HSCROLL);gd(WS_SYSMENU);gd(WS_THICKFRAME);gd(WS_GROUP);gd(WS_TABSTOP);gd(WS_MINIMIZEBOX);gd(WS_MAXIMIZEBOX);gd(WS_TILED);gd(WS_ICONIC);gd(WS_SIZEBOX);gd(WS_TILEDWINDOW);gd(WS_OVERLAPPEDWINDOW);gd(WS_POPUPWINDOW);gd(WS_CHILDWINDOW);gd(WS_EX_DLGMODALFRAME);gd(WS_EX_NOPARENTNOTIFY);gd(WS_EX_TOPMOST);gd(WS_EX_ACCEPTFILES);gd(WS_EX_TRANSPARENT);gd(WS_EX_MDICHILD);gd(WS_EX_TOOLWINDOW);gd(WS_EX_WINDOWEDGE);gd(WS_EX_CLIENTEDGE);gd(WS_EX_CONTEXTHELP);gd(WS_EX_RIGHT);gd(WS_EX_LEFT);gd(WS_EX_RTLREADING);gd(WS_EX_LTRREADING);gd(WS_EX_LEFTSCROLLBAR);gd(WS_EX_RIGHTSCROLLBAR);gd(WS_EX_CONTROLPARENT);gd(WS_EX_STATICEDGE);gd(WS_EX_APPWINDOW);gd(WS_EX_OVERLAPPEDWINDOW);gd(WS_EX_PALETTEWINDOW);gd(WS_EX_LAYERED);gd(WS_EX_NOINHERITLAYOUT);gd(WS_EX_NOREDIRECTIONBITMAP);gd(WS_EX_LAYOUTRTL);gd(WS_EX_COMPOSITED);gd(WS_EX_NOACTIVATE);gd(WS_ACTIVECAPTION);

  /*
   * Class styles
   */
  gd(CS_VREDRAW);gd(CS_HREDRAW);gd(CS_DBLCLKS);gd(CS_OWNDC);gd(CS_CLASSDC);gd(CS_PARENTDC);gd(CS_NOCLOSE);gd(CS_SAVEBITS);gd(CS_BYTEALIGNCLIENT);gd(CS_BYTEALIGNWINDOW);gd(CS_GLOBALCLASS);gd(CS_IME);gd(CS_DROPSHADOW);

  /*
   * Button Control Styles
   */
  gd(BS_PUSHBUTTON);gd(BS_DEFPUSHBUTTON);gd(BS_CHECKBOX);gd(BS_AUTOCHECKBOX);gd(BS_RADIOBUTTON);gd(BS_3STATE);gd(BS_AUTO3STATE);gd(BS_GROUPBOX);gd(BS_USERBUTTON);gd(BS_AUTORADIOBUTTON);gd(BS_PUSHBOX);gd(BS_OWNERDRAW);gd(BS_TYPEMASK);gd(BS_LEFTTEXT);gd(BS_TEXT);gd(BS_ICON);gd(BS_BITMAP);gd(BS_LEFT);gd(BS_RIGHT);gd(BS_CENTER);gd(BS_TOP);gd(BS_BOTTOM);gd(BS_VCENTER);gd(BS_PUSHLIKE);gd(BS_MULTILINE);gd(BS_NOTIFY);gd(BS_FLAT);gd(BS_RIGHTBUTTON);

  /*
   * Combo Box styles
   */
  gd(CBS_SIMPLE);gd(CBS_DROPDOWN);gd(CBS_DROPDOWNLIST);gd(CBS_OWNERDRAWFIXED);gd(CBS_OWNERDRAWVARIABLE);gd(CBS_AUTOHSCROLL);gd(CBS_OEMCONVERT);gd(CBS_SORT);gd(CBS_HASSTRINGS);gd(CBS_NOINTEGRALHEIGHT);gd(CBS_DISABLENOSCROLL);gd(CBS_UPPERCASE);gd(CBS_LOWERCASE);

  /*
   * Listbox Styles
   */
  gd(ES_LEFT);gd(ES_CENTER);gd(ES_RIGHT);gd(ES_MULTILINE);gd(ES_UPPERCASE);gd(ES_LOWERCASE);gd(ES_PASSWORD);gd(ES_AUTOVSCROLL);gd(ES_AUTOHSCROLL);gd(ES_NOHIDESEL);gd(ES_OEMCONVERT);gd(ES_READONLY);gd(ES_WANTRETURN);gd(ES_NUMBER);

  /*
   * Edit Control Styles
   */
  gd(LBS_NOTIFY);gd(LBS_SORT);gd(LBS_NOREDRAW);gd(LBS_MULTIPLESEL);gd(LBS_OWNERDRAWFIXED);gd(LBS_OWNERDRAWVARIABLE);gd(LBS_HASSTRINGS);gd(LBS_USETABSTOPS);gd(LBS_NOINTEGRALHEIGHT);gd(LBS_MULTICOLUMN);gd(LBS_WANTKEYBOARDINPUT);gd(LBS_EXTENDEDSEL);gd(LBS_DISABLENOSCROLL);gd(LBS_NODATA);gd(LBS_NOSEL);gd(LBS_COMBOBOX);gd(LBS_STANDARD);

  /*
   * Scroll Bar Styles
   */
  gd(SBS_HORZ);gd(SBS_VERT);gd(SBS_TOPALIGN);gd(SBS_LEFTALIGN);gd(SBS_BOTTOMALIGN);gd(SBS_RIGHTALIGN);gd(SBS_SIZEBOXTOPLEFTALIGN);gd(SBS_SIZEBOXBOTTOMRIGHTALIGN);gd(SBS_SIZEBOX);gd(SBS_SIZEGRIP);

  /*
   * Static Control Constants
   */
  gd(SS_LEFT);gd(SS_CENTER);gd(SS_RIGHT);gd(SS_ICON);gd(SS_BLACKRECT);gd(SS_GRAYRECT);gd(SS_WHITERECT);gd(SS_BLACKFRAME);gd(SS_GRAYFRAME);gd(SS_WHITEFRAME);gd(SS_USERITEM);gd(SS_SIMPLE);gd(SS_LEFTNOWORDWRAP);gd(SS_OWNERDRAW);gd(SS_BITMAP);gd(SS_ENHMETAFILE);gd(SS_ETCHEDHORZ);gd(SS_ETCHEDVERT);gd(SS_ETCHEDFRAME);gd(SS_TYPEMASK);gd(SS_REALSIZECONTROL);gd(SS_NOPREFIX);gd(SS_NOTIFY);gd(SS_CENTERIMAGE);gd(SS_RIGHTJUST);gd(SS_REALSIZEIMAGE);gd(SS_SUNKEN);gd(SS_EDITCONTROL);gd(SS_ENDELLIPSIS);gd(SS_PATHELLIPSIS);gd(SS_WORDELLIPSIS);gd(SS_ELLIPSISMASK);

  /*
   * User Button Notification Codes
   */
  gd(BN_CLICKED);gd(BN_PAINT);gd(BN_HILITE);gd(BN_UNHILITE);gd(BN_DISABLE);gd(BN_DOUBLECLICKED);gd(BN_PUSHED);gd(BN_UNPUSHED);gd(BN_DBLCLK);gd(BN_SETFOCUS);gd(BN_KILLFOCUS);

  /*
   * Button Control Messages
   */
  gd(BM_GETCHECK);gd(BM_SETCHECK);gd(BM_GETSTATE);gd(BM_SETSTATE);gd(BM_SETSTYLE);gd(BM_CLICK);gd(BM_GETIMAGE);gd(BM_SETIMAGE);gd(BM_SETDONTCLICK);

  /*
   * Button State
   */
  gd(BST_UNCHECKED);gd(BST_CHECKED);gd(BST_INDETERMINATE);gd(BST_PUSHED);gd(BST_FOCUS);

  /*
   * key State Masks for Mouse Messages
   */
  gd(MK_LBUTTON);gd(MK_RBUTTON);gd(MK_SHIFT);gd(MK_CONTROL);gd(MK_MBUTTON);gd(MK_XBUTTON1);gd(MK_XBUTTON2);

  /*
   * Virtual Keys
   */
  gd(VK_LBUTTON);gd(VK_RBUTTON);gd(VK_CANCEL);gd(VK_MBUTTON);gd(VK_XBUTTON1);gd(VK_XBUTTON2);gd(VK_BACK);gd(VK_TAB);gd(VK_CLEAR);gd(VK_RETURN);gd(VK_SHIFT);gd(VK_CONTROL);gd(VK_MENU);gd(VK_PAUSE);gd(VK_CAPITAL);gd(VK_KANA);gd(VK_HANGEUL);gd(VK_HANGUL);gd(VK_JUNJA);gd(VK_FINAL);gd(VK_HANJA);gd(VK_KANJI);gd(VK_ESCAPE);gd(VK_CONVERT);gd(VK_NONCONVERT);gd(VK_ACCEPT);gd(VK_MODECHANGE);gd(VK_SPACE);gd(VK_PRIOR);gd(VK_NEXT);gd(VK_END);gd(VK_HOME);gd(VK_LEFT);gd(VK_UP);gd(VK_RIGHT);gd(VK_DOWN);gd(VK_SELECT);gd(VK_PRINT);gd(VK_EXECUTE);gd(VK_SNAPSHOT);gd(VK_INSERT);gd(VK_DELETE);gd(VK_HELP);gd(VK_LWIN);gd(VK_RWIN);gd(VK_APPS);gd(VK_SLEEP);gd(VK_NUMPAD0);gd(VK_NUMPAD1);gd(VK_NUMPAD2);gd(VK_NUMPAD3);gd(VK_NUMPAD4);gd(VK_NUMPAD5);gd(VK_NUMPAD6);gd(VK_NUMPAD7);gd(VK_NUMPAD8);gd(VK_NUMPAD9);gd(VK_MULTIPLY);gd(VK_ADD);gd(VK_SEPARATOR);gd(VK_SUBTRACT);gd(VK_DECIMAL);gd(VK_DIVIDE);gd(VK_F1);gd(VK_F2);gd(VK_F3);gd(VK_F4);gd(VK_F5);gd(VK_F6);gd(VK_F7);gd(VK_F8);gd(VK_F9);gd(VK_F10);gd(VK_F11);gd(VK_F12);gd(VK_F13);gd(VK_F14);gd(VK_F15);gd(VK_F16);gd(VK_F17);gd(VK_F18);gd(VK_F19);gd(VK_F20);gd(VK_F21);gd(VK_F22);gd(VK_F23);gd(VK_F24);gd(VK_NAVIGATION_VIEW);gd(VK_NAVIGATION_MENU);gd(VK_NAVIGATION_UP);gd(VK_NAVIGATION_DOWN);gd(VK_NAVIGATION_LEFT);gd(VK_NAVIGATION_RIGHT);gd(VK_NAVIGATION_ACCEPT);gd(VK_NAVIGATION_CANCEL);gd(VK_NUMLOCK);gd(VK_SCROLL);gd(VK_OEM_NEC_EQUAL);gd(VK_OEM_FJ_JISHO);gd(VK_OEM_FJ_MASSHOU);gd(VK_OEM_FJ_TOUROKU);gd(VK_OEM_FJ_LOYA);gd(VK_OEM_FJ_ROYA);gd(VK_LSHIFT);gd(VK_RSHIFT);gd(VK_LCONTROL);gd(VK_RCONTROL);gd(VK_LMENU);gd(VK_RMENU);gd(VK_BROWSER_BACK);gd(VK_BROWSER_FORWARD);gd(VK_BROWSER_REFRESH);gd(VK_BROWSER_STOP);gd(VK_BROWSER_SEARCH);gd(VK_BROWSER_FAVORITES);gd(VK_BROWSER_HOME);gd(VK_VOLUME_MUTE);gd(VK_VOLUME_DOWN);gd(VK_VOLUME_UP);gd(VK_MEDIA_NEXT_TRACK);gd(VK_MEDIA_PREV_TRACK);gd(VK_MEDIA_STOP);gd(VK_MEDIA_PLAY_PAUSE);gd(VK_LAUNCH_MAIL);gd(VK_LAUNCH_MEDIA_SELECT);gd(VK_LAUNCH_APP1);gd(VK_LAUNCH_APP2);gd(VK_OEM_1);gd(VK_OEM_PLUS);gd(VK_OEM_COMMA);gd(VK_OEM_MINUS);gd(VK_OEM_PERIOD);gd(VK_OEM_2);gd(VK_OEM_3);gd(VK_GAMEPAD_A);gd(VK_GAMEPAD_B);gd(VK_GAMEPAD_X);gd(VK_GAMEPAD_Y);gd(VK_GAMEPAD_RIGHT_SHOULDER);gd(VK_GAMEPAD_LEFT_SHOULDER);gd(VK_GAMEPAD_LEFT_TRIGGER);gd(VK_GAMEPAD_RIGHT_TRIGGER);gd(VK_GAMEPAD_DPAD_UP);gd(VK_GAMEPAD_DPAD_DOWN);gd(VK_GAMEPAD_DPAD_LEFT);gd(VK_GAMEPAD_DPAD_RIGHT);gd(VK_GAMEPAD_MENU);gd(VK_GAMEPAD_VIEW);gd(VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON);gd(VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON);gd(VK_GAMEPAD_LEFT_THUMBSTICK_UP);gd(VK_GAMEPAD_LEFT_THUMBSTICK_DOWN);gd(VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT);gd(VK_GAMEPAD_LEFT_THUMBSTICK_LEFT);gd(VK_GAMEPAD_RIGHT_THUMBSTICK_UP);gd(VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN);gd(VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT);gd(VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT);gd(VK_OEM_4);gd(VK_OEM_5);gd(VK_OEM_6);gd(VK_OEM_7);gd(VK_OEM_8);gd(VK_OEM_AX);gd(VK_OEM_102);gd(VK_ICO_HELP);gd(VK_ICO_00);gd(VK_PROCESSKEY);gd(VK_ICO_CLEAR);gd(VK_PACKET);gd(VK_OEM_RESET);gd(VK_OEM_JUMP);gd(VK_OEM_PA1);gd(VK_OEM_PA2);gd(VK_OEM_PA3);gd(VK_OEM_WSCTRL);gd(VK_OEM_CUSEL);gd(VK_OEM_ATTN);gd(VK_OEM_FINISH);gd(VK_OEM_COPY);gd(VK_OEM_AUTO);gd(VK_OEM_ENLW);gd(VK_OEM_BACKTAB);gd(VK_ATTN);gd(VK_CRSEL);gd(VK_EXSEL);gd(VK_EREOF);gd(VK_PLAY);gd(VK_ZOOM);gd(VK_NONAME);gd(VK_PA1);gd(VK_OEM_CLEAR);
global.Set("VK_0", 48);global.Set("VK_1", 49);global.Set("VK_2", 50);global.Set("VK_3", 51);global.Set("VK_4", 52);global.Set("VK_5", 53);global.Set("VK_6", 54);global.Set("VK_7", 55);global.Set("VK_8", 56);global.Set("VK_9", 57);global.Set("VK_A", 65);global.Set("VK_B", 66);global.Set("VK_C", 67);global.Set("VK_D", 68);global.Set("VK_E", 69);global.Set("VK_F", 70);global.Set("VK_G", 71);global.Set("VK_H", 72);global.Set("VK_I", 73);global.Set("VK_J", 74);global.Set("VK_K", 75);global.Set("VK_L", 76);global.Set("VK_M", 77);global.Set("VK_N", 78);global.Set("VK_O", 79);global.Set("VK_P", 80);global.Set("VK_Q", 81);global.Set("VK_R", 82);global.Set("VK_S", 83);global.Set("VK_T", 84);global.Set("VK_U", 85);global.Set("VK_V", 86);global.Set("VK_W", 87);global.Set("VK_X", 88);global.Set("VK_Y", 89);global.Set("VK_Z", 90);

  nm_retu;
}
